# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pnj',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('url_id', models.PositiveIntegerField()),
                ('visible', models.BooleanField()),
                ('img_id', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(default=20)),
                ('cast', models.PositiveIntegerField(choices=[(1, 'Fongeux'), (2, 'Monteurs'), (3, 'Rapiats'), (4, 'Pisteurs')])),
                ('attributes', models.CharField(default='0,0,0,0,0,0,0,0,0', max_length=100)),
                ('skills', models.CharField(blank=True, max_length=1200)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('stuff', models.CharField(blank=True, max_length=1200)),
                ('more', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
    ]
