# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 13:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEntity',
            fields=[
                ('uid', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('img_id', models.CharField(blank=True, max_length=255, null=True)),
                ('img_src', models.CharField(blank=True, max_length=800, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('more', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter_date', models.CharField(blank=True, max_length=255, null=True)),
                ('img_id', models.CharField(blank=True, max_length=255, null=True)),
                ('img_legend', models.CharField(blank=True, max_length=255, null=True)),
                ('img_link', models.CharField(blank=True, max_length=255, null=True)),
                ('corpus', models.TextField(blank=True, db_index=True, null=True)),
                ('order_position', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HomeItems',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('img_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_position', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ia_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRecipes',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('ia_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ia', models.CharField(blank=True, max_length=255, null=True)),
                ('iaq', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('ib_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ib', models.CharField(blank=True, max_length=255, null=True)),
                ('ibq', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('ic_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ic', models.CharField(blank=True, max_length=255, null=True)),
                ('icq', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('more', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PjNote',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_unique', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('more', models.CharField(blank=True, max_length=2500, null=True)),
                ('related_job', models.ManyToManyField(related_name='related_job', to='vsite.Jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('gameentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vsite.GameEntity')),
                ('puissance', models.PositiveIntegerField()),
                ('vigueur', models.PositiveIntegerField()),
                ('dexterite', models.PositiveIntegerField()),
                ('perception', models.PositiveIntegerField()),
                ('charisme', models.PositiveIntegerField()),
                ('astuce', models.PositiveIntegerField()),
                ('volonte', models.PositiveIntegerField()),
                ('intelligence', models.PositiveIntegerField()),
                ('essence', models.PositiveIntegerField()),
            ],
            bases=('vsite.gameentity',),
        ),
        migrations.CreateModel(
            name='IgCreature',
            fields=[
                ('gameentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vsite.GameEntity')),
                ('puissance', models.PositiveIntegerField()),
                ('vigueur', models.PositiveIntegerField()),
                ('dexterite', models.PositiveIntegerField()),
                ('perception', models.PositiveIntegerField()),
                ('charisme', models.PositiveIntegerField()),
                ('astuce', models.PositiveIntegerField()),
                ('volonte', models.PositiveIntegerField()),
                ('intelligence', models.PositiveIntegerField()),
                ('essence', models.PositiveIntegerField()),
            ],
            bases=('vsite.gameentity',),
        ),
        migrations.CreateModel(
            name='Phenomenon',
            fields=[
                ('gameentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vsite.GameEntity')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
            bases=('vsite.gameentity',),
        ),
        migrations.CreateModel(
            name='PjCharacter',
            fields=[
                ('gameentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vsite.GameEntity')),
                ('puissance', models.PositiveIntegerField()),
                ('vigueur', models.PositiveIntegerField()),
                ('dexterite', models.PositiveIntegerField()),
                ('perception', models.PositiveIntegerField()),
                ('charisme', models.PositiveIntegerField()),
                ('astuce', models.PositiveIntegerField()),
                ('volonte', models.PositiveIntegerField()),
                ('intelligence', models.PositiveIntegerField()),
                ('essence', models.PositiveIntegerField()),
                ('first_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pj_fjob', to='vsite.Jobs')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pj_owner', to=settings.AUTH_USER_MODEL)),
                ('second_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pj_sjob', to='vsite.Jobs')),
            ],
            bases=('vsite.gameentity',),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('gameentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vsite.GameEntity')),
                ('category', models.CharField(choices=[('Havre', 'Havre'), ('Ruine', 'Ruine'), ('Bunker', 'Bunker'), ('Cache', 'Cache'), ('Abri', 'Abri')], max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
            bases=('vsite.gameentity',),
        ),
        migrations.CreateModel(
            name='Pnj',
            fields=[
                ('gameentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vsite.GameEntity')),
                ('puissance', models.PositiveIntegerField()),
                ('vigueur', models.PositiveIntegerField()),
                ('dexterite', models.PositiveIntegerField()),
                ('perception', models.PositiveIntegerField()),
                ('charisme', models.PositiveIntegerField()),
                ('astuce', models.PositiveIntegerField()),
                ('volonte', models.PositiveIntegerField()),
                ('intelligence', models.PositiveIntegerField()),
                ('essence', models.PositiveIntegerField()),
                ('first_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnj_fjob', to='vsite.Jobs')),
                ('second_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnj_sjob', to='vsite.Jobs')),
            ],
            bases=('vsite.gameentity',),
        ),
        migrations.AddField(
            model_name='pjnote',
            name='note_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_id', to='vsite.GameEntity'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_uid', to='vsite.GameEntity'),
        ),
        migrations.AddField(
            model_name='item',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_uid', to='vsite.ItemRecipes'),
        ),
        migrations.AddField(
            model_name='pjnote',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char_id', to='vsite.PjCharacter'),
        ),
        migrations.AddField(
            model_name='igcreature',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Place_uid', to='vsite.Place'),
        ),
    ]
