# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='job_type',
        ),
    ]
