# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(default=0, max_length=2048),
            preserve_default=False,
        ),
    ]
