# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0002_remove_jobs_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnj',
            name='owner',
        ),
    ]
