# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0002_auto_20170104_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
