# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0003_auto_20170104_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('Changelog', 'Changelog'), ('Blog', 'Blog')], max_length=100)),
                ('corpus', models.TextField()),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
