# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.CharField(max_length=100)),
                ('corpus', models.CharField(max_length=400)),
                ('created_date', models.DateField(auto_now=True)),
                ('reverted', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
