# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0004_auto_20161231_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='stuff',
        ),
        migrations.RemoveField(
            model_name='pjcharacter',
            name='stuff',
        ),
        migrations.RemoveField(
            model_name='pnj',
            name='stuff',
        ),
    ]
