# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0005_pnj_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pnj_comment',
            new_name='pnj_note',
        ),
    ]
