# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0005_auto_20170105_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='file',
        ),
    ]
