# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0005_auto_20170102_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngameCreature',
            fields=[
                ('gameentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vsite.GameEntity')),
                ('puissance', models.PositiveIntegerField()),
                ('vigueur', models.PositiveIntegerField()),
                ('dexterite', models.PositiveIntegerField()),
                ('perception', models.PositiveIntegerField()),
                ('charisme', models.PositiveIntegerField()),
                ('astuce', models.PositiveIntegerField()),
                ('volonte', models.PositiveIntegerField()),
                ('intelligence', models.PositiveIntegerField()),
                ('essence', models.PositiveIntegerField()),
            ],
            bases=('vsite.gameentity',),
        ),
    ]
