# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0006_auto_20160822_2012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pnj_note',
            new_name='pj_note',
        ),
    ]
