# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0006_ingamecreature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngameCreature',
            new_name='IgCreature',
        ),
    ]
