# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0007_auto_20170102_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='igcreature',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Place_uid', to='vsite.Place'),
            preserve_default=False,
        ),
    ]
