# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0007_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
