# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0007_auto_20160823_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='pj_note',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pj_note',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
