# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0008_igcreature_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='igcreature',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crea_owner_id', to='vsite.PjCharacter'),
        ),
    ]
