# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0008_auto_20170105_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='complete_file',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='external_link',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='internal_link',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='legend',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='legend_alt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
