# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0008_auto_20160823_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pj_note',
            name='published_date',
        ),
    ]
