# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0009_auto_20170105_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='complete_file',
            field=models.CharField(blank=True, default='#', max_length=500, null=True),
        ),
    ]
