# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0009_igcreature_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igcreature',
            name='owner',
        ),
    ]
