# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vsite', '0009_remove_pj_note_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField()),
                ('quality', models.PositiveIntegerField()),
                ('rarity', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=2048)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='item_blueprint',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField()),
                ('recipe', models.CharField(max_length=2048)),
                ('rarity', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='pnj',
            name='is_pj',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pnj',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='blueprint_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bleuprint_uid', to='vsite.item_blueprint'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pj_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
