# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0010_auto_20160831_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_items',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('img_id', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pnj',
            name='cast',
            field=models.PositiveIntegerField(choices=[(1, 'Scaveux'), (2, 'Fongerbeux'), (3, 'Chassoux'), (4, 'Soldards'), (5, 'Brassoux'), (6, 'Chamans')]),
        ),
    ]
