# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0010_auto_20170105_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='related_job',
        ),
        migrations.AddField(
            model_name='jobs',
            name='related_skills',
            field=models.ManyToManyField(related_name='related_skills', to='vsite.Skills'),
        ),
    ]
