# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0011_auto_20170105_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameentity',
            name='img_id',
        ),
        migrations.RemoveField(
            model_name='gameentity',
            name='img_src',
        ),
        migrations.RemoveField(
            model_name='gamelog',
            name='img_id',
        ),
        migrations.RemoveField(
            model_name='gamelog',
            name='img_legend',
        ),
        migrations.RemoveField(
            model_name='gamelog',
            name='img_link',
        ),
        migrations.RemoveField(
            model_name='homeitems',
            name='img_id',
        ),
        migrations.AddField(
            model_name='gameentity',
            name='img_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_name', to='vsite.Image'),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='img_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_name_gl', to='vsite.Image'),
        ),
        migrations.AddField(
            model_name='homeitems',
            name='img_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_name_hi', to='vsite.Image'),
        ),
    ]
