# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0011_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrecipes',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='itemrecipes',
            name='leather',
        ),
        migrations.RemoveField(
            model_name='itemrecipes',
            name='metal',
        ),
        migrations.RemoveField(
            model_name='itemrecipes',
            name='plastic',
        ),
        migrations.RemoveField(
            model_name='itemrecipes',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='itemrecipes',
            name='rock',
        ),
        migrations.RemoveField(
            model_name='itemrecipes',
            name='wood',
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='ia_type',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='ib_type',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='ic_type',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='ia',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='iaq',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='ib',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='ic',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
