# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0011_auto_20161121_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_items',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
