# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0012_home_items_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnj',
            name='age',
        ),
        migrations.RemoveField(
            model_name='pnj',
            name='family',
        ),
        migrations.AddField(
            model_name='pnj',
            name='is_creature',
            field=models.BooleanField(default=False),
        ),
    ]
