# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0012_auto_20170103_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrecipes',
            name='iaq',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='ibq',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='icq',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
