# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0013_auto_20170103_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrecipes',
            name='ia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='ia_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='ib',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='ib_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='ic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='ic_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
