# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0013_auto_20161121_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_items',
            name='order_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
