# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0014_auto_20170105_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameentity',
            old_name='img_name',
            new_name='ManyToManyField',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='img_name',
            new_name='ManyToManyField',
        ),
        migrations.RemoveField(
            model_name='homeitems',
            name='img_name',
        ),
        migrations.AddField(
            model_name='homeitems',
            name='img_name',
            field=models.ManyToManyField(blank=True, related_name='img_name_hi', to='vsite.Image'),
        ),
    ]
