# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0015_pj_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pj_character',
            name='first_job',
            field=models.CharField(choices=[('Scaveux', 'Scaveux'), ('Fongerbeux', 'Fongerbeux'), ('Chassoux', 'Chassoux'), ('Soldards', 'Soldards'), ('Brassoux', 'Brassoux'), ('Chamans', 'Chamans')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pj_character',
            name='second_job',
            field=models.CharField(choices=[('Boisard', 'Boisard'), ('Forgeard', 'Forgeard'), ('Chefton', 'Chefton'), ('Soigneur', 'Soigneur'), ('Leveur', 'Leveur')], max_length=255),
        ),
    ]
