# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0016_auto_20170105_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeitems',
            name='img_name',
            field=models.ManyToManyField(blank=True, related_name='img_name_hi', to='vsite.Image'),
        ),
    ]
