# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0016_auto_20161121_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pj_character',
            old_name='player_uid',
            new_name='owner',
        ),
    ]
