# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0017_auto_20161121_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_log',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('img_id', models.CharField(blank=True, max_length=255, null=True)),
                ('img_legend', models.CharField(blank=True, max_length=255, null=True)),
                ('img_link', models.CharField(blank=True, max_length=255, null=True)),
                ('corpus', models.TextField(blank=True, db_index=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='pj_character',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
