# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0018_auto_20161122_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_log',
            name='order_position',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
