# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0019_game_log_order_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_log',
            name='campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game_log',
            name='chapter_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
