# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0019_auto_20170105_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelog',
            old_name='ManyToManyField',
            new_name='img_name',
        ),
    ]
