# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vsite', '0020_auto_20161122_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Métier principal', 'Métier principal'), ('Métier secondaire', 'Métier secondaire')], max_length=255)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('more', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PjCharacter',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('img_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('puissance', models.PositiveIntegerField()),
                ('vigueur', models.PositiveIntegerField()),
                ('dexterite', models.PositiveIntegerField()),
                ('perception', models.PositiveIntegerField()),
                ('charisme', models.PositiveIntegerField()),
                ('astuce', models.PositiveIntegerField()),
                ('volonte', models.PositiveIntegerField()),
                ('intelligence', models.PositiveIntegerField()),
                ('essence', models.PositiveIntegerField()),
                ('stuff', models.CharField(blank=True, max_length=1200)),
                ('more', models.CharField(blank=True, max_length=2500, null=True)),
                ('first_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pj_fjob', to='vsite.Jobs')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pj_owner', to=settings.AUTH_USER_MODEL)),
                ('second_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pj_sjob', to='vsite.Jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('more', models.CharField(blank=True, max_length=2500, null=True)),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_job', to='vsite.Jobs')),
            ],
        ),
        migrations.RenameModel(
            old_name='game_log',
            new_name='GameLog',
        ),
        migrations.RenameModel(
            old_name='home_items',
            new_name='HomeItems',
        ),
        migrations.RenameModel(
            old_name='item_blueprint',
            new_name='ItemRecipes',
        ),
        migrations.RenameModel(
            old_name='pj_note',
            new_name='PjNote',
        ),
        migrations.RemoveField(
            model_name='pj_character',
            name='owner',
        ),
        migrations.RenameField(
            model_name='pjnote',
            old_name='poster_id',
            new_name='poster',
        ),
        migrations.RemoveField(
            model_name='item',
            name='blueprint_uid',
        ),
        migrations.RemoveField(
            model_name='pjnote',
            name='pnj_id',
        ),
        migrations.RemoveField(
            model_name='pnj',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='pnj',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='pnj',
            name='is_creature',
        ),
        migrations.RemoveField(
            model_name='pnj',
            name='is_pj',
        ),
        migrations.RemoveField(
            model_name='pnj',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='pnj',
            name='visible',
        ),
        migrations.AddField(
            model_name='item',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_uid', to='vsite.ItemRecipes'),
        ),
        migrations.AddField(
            model_name='pjnote',
            name='pnj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnj_id', to='vsite.Pnj'),
        ),
        migrations.AddField(
            model_name='pnj',
            name='astuce',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnj',
            name='charisme',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnj',
            name='dexterite',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnj',
            name='essence',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnj',
            name='intelligence',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnj',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnj_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pnj',
            name='perception',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnj',
            name='puissance',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnj',
            name='vigueur',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnj',
            name='volonte',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pj_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pnj',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pnj',
            name='img_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pnj',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='pj_character',
        ),
        migrations.AddField(
            model_name='pnj',
            name='first_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnj_fjob', to='vsite.Jobs'),
        ),
        migrations.AddField(
            model_name='pnj',
            name='second_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnj_sjob', to='vsite.Jobs'),
        ),
    ]
