# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0020_auto_20170105_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='is_announce',
            field=models.BooleanField(default=False),
        ),
    ]
