# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0023_auto_20161123_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnj',
            name='is_creature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pjnote',
            name='pnj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnj_id', to='vsite.Pnj'),
        ),
    ]
