# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0024_auto_20170106_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrecipes',
            name='identifier',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='level',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
