# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0025_auto_20170108_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contained_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_contained_by', to='vsite.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_container',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='is_container',
            field=models.BooleanField(default=False),
        ),
    ]
