# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0026_auto_20170111_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img_name',
            field=models.ManyToManyField(blank=True, related_name='img_name_igi', to='vsite.Image'),
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='img_name',
            field=models.ManyToManyField(blank=True, related_name='img_name_ir', to='vsite.Image'),
        ),
    ]
