# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0026_auto_20161202_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrecipes',
            old_name='inga',
            new_name='ia',
        ),
        migrations.RenameField(
            model_name='itemrecipes',
            old_name='level',
            new_name='iaq',
        ),
        migrations.RenameField(
            model_name='itemrecipes',
            old_name='ingb',
            new_name='ib',
        ),
        migrations.RenameField(
            model_name='itemrecipes',
            old_name='ingc',
            new_name='ic',
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='fiber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='ibq',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='icq',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='item_type',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='leather',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='metal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='plastic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='rock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemrecipes',
            name='wood',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='rarity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pjnote',
            name='pnj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnj_id', to='vsite.Pnj'),
        ),
    ]
