# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0028_auto_20170116_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='geom',
        ),
        migrations.AddField(
            model_name='place',
            name='close_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_close_to', to='vsite.Place'),
        ),
    ]
