# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0029_auto_20170119_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='close_to',
        ),
        migrations.AddField(
            model_name='place',
            name='close_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='_place_close_to_+', to='vsite.Place'),
        ),
    ]
