# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0029_auto_20161202_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrecipes',
            name='fiber',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='leather',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='metal',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='plastic',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='rock',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemrecipes',
            name='wood',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pjnote',
            name='pnj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnj_id', to='vsite.Pnj'),
        ),
    ]
