# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0030_auto_20170119_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjcharacter',
            name='current_body',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pjcharacter',
            name='current_instinct',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pjcharacter',
            name='current_spirit',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
