# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0030_auto_20161202_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='level',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rarity',
        ),
        migrations.AddField(
            model_name='item',
            name='ia_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ib_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ic_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pjnote',
            name='pnj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnj_id', to='vsite.Pnj'),
        ),
    ]
