# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0032_auto_20170119_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='source_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_entity', to='vsite.GameEntity'),
        ),
        migrations.AddField(
            model_name='igcreature',
            name='current_body',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='igcreature',
            name='current_instinct',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='igcreature',
            name='current_spirit',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
