# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0033_auto_20170126_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnj',
            name='current_body',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnj',
            name='current_instinct',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnj',
            name='current_spirit',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnj',
            name='location',
            field=models.ForeignKey(default=4166174283716368373, on_delete=django.db.models.deletion.CASCADE, related_name='pnj_location', to='vsite.Place'),
            preserve_default=False,
        ),
    ]
