# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0033_auto_20161203_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pjnote',
            name='pnj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnj_id', to='vsite.Pnj'),
        ),
        migrations.AlterField(
            model_name='pjnote',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char_id', to='vsite.PjCharacter'),
        ),
    ]
