# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0034_auto_20170126_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableLog',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_entity', to='vsite.GameEntity')),
            ],
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='source_entity',
        ),
    ]
