# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-02 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0036_gameglobal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameglobal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gameglobal',
            name='value',
        ),
        migrations.AddField(
            model_name='gameglobal',
            name='current_entities',
            field=models.ManyToManyField(blank=True, related_name='current_game_entities', to='vsite.GameEntity'),
        ),
        migrations.AddField(
            model_name='gameglobal',
            name='current_gamelog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_game_log', to='vsite.GameLog'),
        ),
        migrations.AddField(
            model_name='gameglobal',
            name='current_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_place_id', to='vsite.Place'),
        ),
        migrations.AddField(
            model_name='gameglobal',
            name='game_is_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameglobal',
            name='next_game',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
