# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 15:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0037_auto_20161218_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phenomenon',
            fields=[
                ('gid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('img_id', models.CharField(blank=True, max_length=255, null=True)),
                ('img_src', models.CharField(blank=True, max_length=800, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('more', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('gid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('img_id', models.CharField(blank=True, max_length=255, null=True)),
                ('img_src', models.CharField(blank=True, max_length=800, null=True)),
                ('category', models.CharField(choices=[('Havre', 'Havre'), ('Ruine', 'Ruine'), ('Bunker', 'Bunker'), ('Cache', 'Cache'), ('Abri', 'Abri')], max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('more', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='pjnote',
            name='pnj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnj_id', to='vsite.Pnj'),
        ),
    ]
