# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 15:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0038_auto_20161218_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('img_id', models.CharField(blank=True, max_length=255, null=True)),
                ('img_src', models.CharField(blank=True, max_length=800, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('puissance', models.PositiveIntegerField()),
                ('vigueur', models.PositiveIntegerField()),
                ('dexterite', models.PositiveIntegerField()),
                ('perception', models.PositiveIntegerField()),
                ('charisme', models.PositiveIntegerField()),
                ('astuce', models.PositiveIntegerField()),
                ('volonte', models.PositiveIntegerField()),
                ('intelligence', models.PositiveIntegerField()),
                ('essence', models.PositiveIntegerField()),
                ('stuff', models.CharField(blank=True, max_length=1200)),
                ('more', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='phenomenon',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='pjnote',
            name='pnj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnj_id', to='vsite.Pnj'),
        ),
        migrations.AlterField(
            model_name='place',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
