# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsite', '0040_auto_20161228_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pjnote',
            name='pnj',
        ),
        migrations.AddField(
            model_name='pjnote',
            name='note_target',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
